version: '3.8'

services:
  managerapp:
    build:
      context: .
      dockerfile: ManagerApp/Dockerfile
    container_name: manager-app
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
