networks:
  app-network:
    driver: bridge

services:
  postgre:
    image: postgres:latest
    container_name: postgre
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgre_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network  

  auth-service:  
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: auth-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresConnection=Host=postgre;Port=5432;Database=mydb;Username=myuser;Password=mypassword
    depends_on:
      - postgre
    restart: always
    networks:
      - app-network  

  manager-app:  
    build:
      context: .
      dockerfile: ManagerApp/Dockerfile
    container_name: manager-app
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AuthService__BaseUrl=http://auth-service:8080  
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    depends_on:
      - auth-service
    restart: always
    networks:
      - app-network  
    volumes:
      - data_protection:/var/data-protection  

volumes:
  postgre_data:
  data_protection:
