name: Deploy with Docker Hub

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🏗️ Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Сборка и загрузка образов в Docker Hub
        run: |
          set -e
          
          VERSION=${{ github.run_number }}  

          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/auth-service:$VERSION ./AuthService
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:$VERSION
          docker tag ${{ secrets.DOCKER_USERNAME }}/auth-service:$VERSION ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/order-service:$VERSION ./OrderService
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:$VERSION
          docker tag ${{ secrets.DOCKER_USERNAME }}/order-service:$VERSION ${{ secrets.DOCKER_USERNAME }}/order-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/btu-calc-service:$VERSION ./BTUCalcService
          docker push ${{ secrets.DOCKER_USERNAME }}/btu-calc-service:$VERSION
          docker tag ${{ secrets.DOCKER_USERNAME }}/btu-calc-service:$VERSION ${{ secrets.DOCKER_USERNAME }}/btu-calc-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/btu-calc-service:latest

          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/manager-app:$VERSION ./ManagerApp
          docker push ${{ secrets.DOCKER_USERNAME }}/manager-app:$VERSION
          docker tag ${{ secrets.DOCKER_USERNAME }}/manager-app:$VERSION ${{ secrets.DOCKER_USERNAME }}/manager-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/manager-app:latest
