name: Deploy with Docker Hub

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Клонирование репозитория
        uses: actions/checkout@v3

      - name: ✅ Проверка переменных перед аутентификацией
        run: |
          set -e  # Остановка при первой ошибке

          echo "🔍 Проверка переменных..."
          
          # Убираем возможные пробелы и переносы строк
          DOCKER_USER_CLEAN=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr -d '[:space:]')

          # Проверяем, что `DOCKER_USERNAME` задан
          if [[ -z "$DOCKER_USER_CLEAN" ]]; then
            echo "❌ Ошибка: DOCKER_USERNAME не задан в GitHub Secrets или содержит пробелы!"
            exit 1
          fi

          # Проверяем, что `DOCKER_PASSWORD` задан
          if [[ -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "❌ Ошибка: DOCKER_PASSWORD не задан в GitHub Secrets!"
            exit 1
          fi

          echo "✅ Все переменные заданы и корректны!"
          echo "🔹 DOCKER_USERNAME: $DOCKER_USER_CLEAN (без пробелов)"

      - name: 🏗️ Логин в Docker Hub
        run: |
          echo "🔑 Авторизация в Docker Hub..."
          DOCKER_USER_CLEAN=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr -d '[:space:]')
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USER_CLEAN" --password-stdin
          echo "✅ Успешно авторизовались в Docker Hub!"

      - name: 📂 Проверка структуры репозитория
        run: |
          echo "🔍 Проверка директорий сервисов перед сборкой..."
          for SERVICE in AuthService OrderService BTUCalcService ManagerApp; do
            if [ ! -d "./$SERVICE" ]; then
              echo "❌ Ошибка: Директория $SERVICE не найдена!"
              exit 1
            fi
          done
          echo "✅ Все директории найдены!"
          echo "📁 Структура проекта:"
          ls -R

      - name: 📦 Сборка и загрузка образов в Docker Hub
        run: |
          set -e  # Остановка выполнения при ошибке

          # Генерация версии на основе номера сборки GitHub Actions
          VERSION="${{ github.run_number }}"  

          echo "🔹 Используем версию: $VERSION"

          # Функция для сборки и загрузки образа
          build_and_push() {
            local SERVICE_NAME=$1
            local SERVICE_PATH=$2

            echo "🚀 Начало сборки образа: $SERVICE_NAME"
            if [ ! -f "$SERVICE_PATH/Dockerfile" ]; then
              echo "❌ Ошибка: Файл Dockerfile отсутствует в $SERVICE_PATH!"
              exit 1
            fi

            echo "📁 Проверяем файлы в $SERVICE_PATH перед сборкой"
            ls -l "$SERVICE_PATH"

            echo "🛠️ Запускаем сборку Docker-образа"
            docker build --no-cache -t "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION" -f "$SERVICE_PATH/Dockerfile" .
            if [ $? -ne 0 ]; then
              echo "❌ Ошибка: Сборка образа $SERVICE_NAME завершилась неудачно!"
              exit 1
            fi
            echo "✅ Образ $SERVICE_NAME:$VERSION успешно собран"

            echo "📤 Загрузка образа в Docker Hub: $SERVICE_NAME:$VERSION"
            docker push "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION"
            if [ $? -ne 0 ]; then
              echo "❌ Ошибка: Загрузка образа $SERVICE_NAME завершилась неудачно!"
              exit 1
            fi
            echo "✅ Образ $SERVICE_NAME:$VERSION загружен в Docker Hub"

            echo "🔄 Обновление latest-тега для $SERVICE_NAME"
            docker tag "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION" "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest"
            docker push "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest"
            if [ $? -ne 0 ]; then
              echo "❌ Ошибка: Обновление latest-тега $SERVICE_NAME завершилось неудачно!"
              exit 1
            fi
            echo "✅ Обновлен latest-тег для $SERVICE_NAME"
          }

          # Вызываем функцию для каждого микросервиса
          build_and_push "auth-service" "AuthService"
          build_and_push "order-service" "OrderService"
          build_and_push "btu-calc-service" "BTUCalcService"
          build_and_push "manager-app" "ManagerApp"

      - name: ✅ Развертывание завершено
        run: echo "🎉 Все образы успешно загружены в Docker Hub!"
