name: Deploy with Docker Hub

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🏗️ Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Сборка и загрузка образов в Docker Hub
        run: |
          set -e  # Остановка выполнения при первой ошибке

          # Генерация версии на основе номера сборки GitHub Actions
          VERSION="${{ github.run_number }}"  

          echo "🔹 Используем версию: $VERSION"

          build_and_push() {
            local SERVICE_NAME=$1
            local SERVICE_PATH=$2

            echo "🚀 Сборка образа: $SERVICE_NAME"
            docker build --no-cache -t "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION" "$SERVICE_PATH"
            
            echo "📤 Загрузка образа в Docker Hub: $SERVICE_NAME:$VERSION"
            docker push "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION"

            echo "🔄 Обновление latest-тега для $SERVICE_NAME"
            docker tag "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$VERSION" "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest"
            docker push "${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest"
          }

          build_and_push "auth-service" "./AuthService"
          build_and_push "order-service" "./OrderService"
          build_and_push "btu-calc-service" "./BTUCalcService"
          build_and_push "manager-app" "./ManagerApp"

      - name: ✅ Развертывание завершено
        run: echo "🎉 Все образы успешно загружены в Docker Hub!"
